# RIsco de credito com regressao logistica

In [2]:
from sklearn.linear_model import LogisticRegression
import pickle

In [5]:
with open('Risco_credito.pkl', 'rb') as f:
    X_risco_credito, y_risco_credito = pickle.load(f)

In [7]:
X_risco_credito

array([[2, 0, 1, 0],
       [1, 0, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 2],
       [1, 1, 1, 2],
       [1, 1, 0, 2],
       [2, 1, 1, 0],
       [2, 1, 0, 2],
       [0, 1, 1, 2],
       [0, 0, 0, 2],
       [0, 0, 1, 0],
       [0, 0, 1, 1],
       [0, 0, 1, 2],
       [2, 0, 1, 1]], dtype=object)

In [8]:
y_risco_credito

array(['alto', 'alto', 'moderado', 'alto', 'baixo', 'baixo', 'alto',
       'moderado', 'baixo', 'baixo', 'alto', 'moderado', 'baixo', 'alto'],
      dtype=object)

In [14]:
import numpy as np
X_risco_credito = np.delete(X_risco_credito, [2, 7, 11], axis=0) # recriar variavel para apagar o atributo moderado pata trabalhar apenas com alto e baixo
y_risco_credito = np.delete(y_risco_credito, [2, 7, 11], axis = 0) # os numeros corresndem aos indices a apagar e 0 para apagr linhas

In [15]:
X_risco_credito # variavel recriado, oberva-se a reducao de registos

array([[2, 0, 1, 0],
       [1, 0, 1, 1],
       [1, 1, 1, 2],
       [1, 1, 1, 2],
       [1, 1, 0, 2],
       [2, 1, 1, 0],
       [0, 1, 1, 2],
       [0, 0, 0, 2],
       [0, 0, 1, 0],
       [0, 0, 1, 2],
       [2, 0, 1, 1]], dtype=object)

In [16]:
y_risco_credito # variavel recriado

array(['alto', 'alto', 'alto', 'baixo', 'baixo', 'alto', 'baixo', 'baixo',
       'alto', 'baixo', 'alto'], dtype=object)

In [19]:
Regressao_risco = LogisticRegression(random_state = 1, max_iter=100)
Regressao_risco.fit(X_risco_credito, y_risco_credito)

LogisticRegression(random_state=1)

In [24]:
Regressao_risco.intercept_ # Visualizar interceptores

array([-0.80828993])

In [25]:
Regressao_risco.coef_ # Verificar os coeficientes

array([[-0.76704533,  0.23906678, -0.47976059,  1.12186218]])

In [29]:
# Historia boa, divida alta, garantias nenhuma e renda >35 ---rico baixo
# Historia ruim, divida alta, garantias adequada e renda <15 ---- riscoalto
previsao = Regressao_risco.predict([[0, 0, 1, 2], [2,0,0,0]])
previsao

array(['baixo', 'alto'], dtype=object)