# PREVISAO DE CUSTOS DE SAUDE COM SVM EM REGRESSAO

In [69]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import LabelEncoder, StandardScaler
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px

In [70]:
df_saude = pd.read_csv('../Dados/Bases_de_dados/plano_saude2.csv')
df_saude

idade  custo
0     18    470
1     23    520
2     28    630
3     33    830
4     38   1150
5     43   1530
6     48   2040
7     53   3080
8     58   5100
9     63  10100

In [71]:
# Divisao entre previsores e classe
X_plano_saude = df_saude.iloc[:, 0:1].values
X_plano_saude

array([[18],
       [23],
       [28],
       [33],
       [38],
       [43],
       [48],
       [53],
       [58],
       [63]], dtype=int64)

In [72]:
X_plano_saude.reshape(-1, 1)

array([[18],
       [23],
       [28],
       [33],
       [38],
       [43],
       [48],
       [53],
       [58],
       [63]], dtype=int64)

In [73]:
X_plano_saude.shape

(10, 1)

In [74]:
y_plano_saude = df_saude.iloc[:, 1].values
y_plano_saude 

array([  470,   520,   630,   830,  1150,  1530,  2040,  3080,  5100,
       10100], dtype=int64)

In [138]:
# EQUILIBRAR A ESCALA ENTRE OS DADOS
otmizar = StandardScaler()
X_plano_saude_scaled = otmizar.fit_transform(X_plano_saude)
otmizar_y = StandardScaler()
y_plano_saude_scaled = otmizar_y.fit_transform(y_plano_saude.reshape(-1, 1)) # converter y para formato de matriz

In [139]:
X_plano_saude_scaled 

array([[-1.5666989 ],
       [-1.21854359],
       [-0.87038828],
       [-0.52223297],
       [-0.17407766],
       [ 0.17407766],
       [ 0.52223297],
       [ 0.87038828],
       [ 1.21854359],
       [ 1.5666989 ]])

In [140]:
y_plano_saude_scaled

array([[-0.72401136],
       [-0.7065653 ],
       [-0.66818397],
       [-0.59839975],
       [-0.48674498],
       [-0.35415495],
       [-0.17620517],
       [ 0.18667281],
       [ 0.8914935 ],
       [ 2.63609918]])

In [141]:
# TREINAMENTO
from sklearn.svm import SVR
treino = SVR(kernel='rbf', degree=18)
treino.fit(X_plano_saude_scaled, y_plano_saude_scaled.ravel() )

SVR(degree=18)

In [142]:
treino.score(X_plano_saude_scaled, y_plano_saude_scaled)

0.7561578176049305

In [143]:
previsao = treino.predict(X_plano_saude_scaled)
previsao 

array([-0.62348071, -0.63291278, -0.57066507, -0.49866508, -0.44637596,
       -0.36326797, -0.13553889,  0.29353246,  0.79122818,  1.09382968])

In [154]:
grafico = px.scatter(x=X_plano_saude_scaled.ravel(), y= y_plano_saude_scaled.ravel())
grafico.add_scatter(x=X_plano_saude_scaled.ravel(), y= previsao, name='REGRESSAO COM SVM')
grafico.show()

In [155]:
treino.predict = [[40]]

In [151]:
# escalonar novo registo
novo = otmizar.transform(novo)
novo

array([[-0.03481553]])

In [153]:
# CONVERSAO DO VALOR ESCALONADO AO VALOR REAL
novo = [[40]]
novo = otmizar.inverse_transform(novo)
novo

array([[614.95626465]])