# PREVISAO DE PRECOS DE CASAS COM REDE NEURAL

In [206]:
import pandas as pd
import numpy as np
import pickle
from sklearn.preprocessing import LabelEncoder, StandardScaler

In [207]:
with open ('prices_houses.pkl', 'rb') as f:
    X_train, X_test, y_train, y_test, otimizador = pickle.load(f)

In [208]:
 X_train.shape,  y_train.shape

((15129, 16), (15129, 1))

In [209]:
 X_test.shape, y_test.shape

((6484, 16), (6484, 1))

In [210]:
from sklearn.neural_network import MLPRegressor

In [211]:
house_price = MLPRegressor(hidden_layer_sizes=(9,9), activation='relu', solver='adam', max_iter=1000)
house_price.fit(X_train,  y_train.ravel())

MLPRegressor(hidden_layer_sizes=(9, 9), max_iter=1000)

In [212]:
house_price.score(X_train, y_train)

0.899089375246803

In [213]:
house_price.score(X_test, y_test)

0.8910348465405152

In [214]:
previsao = house_price.predict(X_test)
previsao 

array([-0.54048449,  2.85892873,  0.01681074, ..., -0.58417675,
       -0.84345781, -0.91102997])

In [215]:
y_test

array([[-0.66215134],
       [ 2.82718328],
       [ 0.05995842],
       ...,
       [-0.43606643],
       [-0.74114487],
       [-0.91002757]])

In [235]:
reais = otimizador.inverse_transform(y_test)
reais 

array([[ 297000.],
       [1578000.],
       [ 562100.],
       ...,
       [ 380000.],
       [ 268000.],
       [ 206000.]])

In [236]:
Previsto = otimizador.inverse_transform(previsao.reshape(1, -1))
Previsto

array([[ 341666.17593263, 1589654.35127147,  546259.67796859, ...,
         325625.93253234,  230439.00464818,  205631.99889239]])

In [237]:
from sklearn.metrics import mean_absolute_error
mean_absolute_error(reais, Previsto.ravel())

73515.46708974018