# PREVISAO DE PRECO DE CASAS COM SVM - REGRESSAO

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.svm import SVR

In [3]:
preco_casas = pd.read_csv('../Dados/Bases_de_dados/house_prices.csv')
preco_casas 

id             date     price  bedrooms  bathrooms  \
0      7129300520  20141013T000000  221900.0         3       1.00   
1      6414100192  20141209T000000  538000.0         3       2.25   
2      5631500400  20150225T000000  180000.0         2       1.00   
3      2487200875  20141209T000000  604000.0         4       3.00   
4      1954400510  20150218T000000  510000.0         3       2.00   
...           ...              ...       ...       ...        ...   
21608   263000018  20140521T000000  360000.0         3       2.50   
21609  6600060120  20150223T000000  400000.0         4       2.50   
21610  1523300141  20140623T000000  402101.0         2       0.75   
21611   291310100  20150116T000000  400000.0         3       2.50   
21612  1523300157  20141015T000000  325000.0         2       0.75   

       sqft_living  sqft_lot  floors  waterfront  view  ...  grade  \
0             1180      5650     1.0           0     0  ...      7   
1             2570      7242     2.0           0     0  ...      7   
2              770     10000     1.0           0     0  ...      6   
3             1960      5000     1.0           0     0  ...      7   
4             1680      8080     1.0           0     0  ...      8   
...            ...       ...     ...         ...   ...  ...    ...   
21608         1530      1131     3.0           0     0  ...      8   
21609         2310      5813     2.0           0     0  ...      8   
21610         1020      1350     2.0           0     0  ...      7   
21611         1600      2388     2.0           0     0  ...      8   
21612         1020      1076     2.0           0     0  ...      7   

       sqft_above  sqft_basement  yr_built  yr_renovated  zipcode      lat  \
0            1180              0      1955             0    98178  47.5112   
1            2170            400      1951          1991    98125  47.7210   
2             770              0      1933             0    98028  47.7379   
3            1050            910      1965             0    98136  47.5208   
4            1680              0      1987             0    98074  47.6168   
...           ...            ...       ...           ...      ...      ...   
21608        1530              0      2009             0    98103  47.6993   
21609        2310              0      2014             0    98146  47.5107   
21610        1020              0      2009             0    98144  47.5944   
21611        1600              0      2004             0    98027  47.5345   
21612        1020              0      2008             0    98144  47.5941   

          long  sqft_living15  sqft_lot15  
0     -122.257           1340        5650  
1     -122.319           1690        7639  
2     -122.233           2720        8062  
3     -122.393           1360        5000  
4     -122.045           1800        7503  
...        ...            ...         ...  
21608 -122.346           1530        1509  
21609 -122.362           1830        7200  
21610 -122.299           1020        2007  
21611 -122.069           1410        1287  
21612 -122.299           1020        1357  

[21613 rows x 21 columns]

In [4]:
# DIVISAO EM  PREVISORES E CLASSE
X_prices = preco_casas.iloc[:, 3:19].values
X_prices

array([[ 3.00000e+00,  1.00000e+00,  1.18000e+03, ...,  9.81780e+04,
         4.75112e+01, -1.22257e+02],
       [ 3.00000e+00,  2.25000e+00,  2.57000e+03, ...,  9.81250e+04,
         4.77210e+01, -1.22319e+02],
       [ 2.00000e+00,  1.00000e+00,  7.70000e+02, ...,  9.80280e+04,
         4.77379e+01, -1.22233e+02],
       ...,
       [ 2.00000e+00,  7.50000e-01,  1.02000e+03, ...,  9.81440e+04,
         4.75944e+01, -1.22299e+02],
       [ 3.00000e+00,  2.50000e+00,  1.60000e+03, ...,  9.80270e+04,
         4.75345e+01, -1.22069e+02],
       [ 2.00000e+00,  7.50000e-01,  1.02000e+03, ...,  9.81440e+04,
         4.75941e+01, -1.22299e+02]])

In [5]:
X_prices.reshape(-1, 1)

array([[ 3.00000e+00],
       [ 1.00000e+00],
       [ 1.18000e+03],
       ...,
       [ 9.81440e+04],
       [ 4.75941e+01],
       [-1.22299e+02]])

In [6]:
X_prices.shape

(21613, 16)

In [7]:
y_prices = preco_casas.iloc[:, 2].values
y_prices

array([221900., 538000., 180000., ..., 402101., 400000., 325000.])

In [8]:
otimizador = StandardScaler()
X_prices = otimizador.fit_transform(X_prices)
y_prices = otimizador.fit_transform(y_prices.reshape(-1, 1))

In [9]:
X_prices 

array([[-0.39873715, -1.44746357, -0.97983502, ...,  1.87015159,
        -0.35257175, -0.30607896],
       [-0.39873715,  0.1756067 ,  0.53363434, ...,  0.87956753,
         1.16156823, -0.74634143],
       [-1.47395936, -1.44746357, -1.42625404, ..., -0.9333882 ,
         1.28353661, -0.13565477],
       ...,
       [-1.47395936, -1.77207762, -1.15404732, ...,  1.23468257,
         0.24788796, -0.60432128],
       [-0.39873715,  0.50022075, -0.52252773, ..., -0.95207846,
        -0.18441416,  1.02891048],
       [-1.47395936, -1.77207762, -1.15404732, ...,  1.23468257,
         0.24572284, -0.60432128]])

In [10]:
y_prices 

array([[-0.86671733],
       [-0.00568792],
       [-0.98084935],
       ...,
       [-0.37586519],
       [-0.38158814],
       [-0.58588173]])

In [11]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X_prices, y_prices, test_size=0.3, random_state=0)

In [27]:
import pickle
with open ('prices_houses.pkl', mode = 'wb') as f:
    pickle.dump([X_train, X_test, y_train, y_test, otimizador], f)

In [16]:
X_train.shape, y_train.shape

((15129, 16), (15129, 1))

In [17]:
X_test.shape, y_test.shape

((6484, 16), (6484, 1))

In [18]:
SVM_treino = SVR(kernel='rbf', degree=15)
SVM_treino.fit(X_train, y_train.ravel())

SVR(degree=15)

In [19]:
# analise do desempenho
SVM_treino.score(X_train, y_train)

0.8123471019341276

In [20]:
SVM_treino.score(X_test, y_test)

0.7375905737120197

In [21]:
previsao = SVM_treino.predict(X_test)
previsao

array([-0.54117066,  3.44942766,  0.02514872, ..., -0.46124207,
       -0.90553429, -1.03007583])

In [22]:
y_test

array([[-0.66215134],
       [ 2.82718328],
       [ 0.05995842],
       ...,
       [-0.43606643],
       [-0.74114487],
       [-0.91002757]])

In [23]:
# CONVERSAO DOS DADOS DE ESCALONADOS A REAIS
y_prices_houses = otimizador.inverse_transform(y_test)
previsoes = otimizador.inverse_transform(previsao.reshape(-1, 1))

In [24]:
# valores reais
y_prices_houses

array([[ 297000.],
       [1578000.],
       [ 562100.],
       ...,
       [ 380000.],
       [ 268000.],
       [ 206000.]])

In [25]:
# previsoes
previsoes

array([[ 341414.27049636],
       [1806437.55061871],
       [ 549320.70563428],
       ...,
       [ 370757.55067656],
       [ 207649.5673257 ],
       [ 161928.03914196]])

In [26]:
from sklearn.metrics import mean_absolute_error
mean_absolute_error(y_prices_houses, previsoes) # com valores convertidos ou sem escalonamento

82486.94464062878