In [31]:
# IMPORTAÇÃO DAS BIBLIOTECAS
import plotly.express as px
import seaborn as sns
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np

In [32]:
#CARREGADMENTO DE DATASET E ATRIBUIÇÃO A UMA VARIAVEL
base_venda_de_casas = pd.read_csv('../Dados/Bases_de_dados/house_prices.csv')
base_venda_de_casas

id             date     price  bedrooms  bathrooms  \
0      7129300520  20141013T000000  221900.0         3       1.00   
1      6414100192  20141209T000000  538000.0         3       2.25   
2      5631500400  20150225T000000  180000.0         2       1.00   
3      2487200875  20141209T000000  604000.0         4       3.00   
4      1954400510  20150218T000000  510000.0         3       2.00   
...           ...              ...       ...       ...        ...   
21608   263000018  20140521T000000  360000.0         3       2.50   
21609  6600060120  20150223T000000  400000.0         4       2.50   
21610  1523300141  20140623T000000  402101.0         2       0.75   
21611   291310100  20150116T000000  400000.0         3       2.50   
21612  1523300157  20141015T000000  325000.0         2       0.75   

       sqft_living  sqft_lot  floors  waterfront  view  ...  grade  \
0             1180      5650     1.0           0     0  ...      7   
1             2570      7242     2.0           0     0  ...      7   
2              770     10000     1.0           0     0  ...      6   
3             1960      5000     1.0           0     0  ...      7   
4             1680      8080     1.0           0     0  ...      8   
...            ...       ...     ...         ...   ...  ...    ...   
21608         1530      1131     3.0           0     0  ...      8   
21609         2310      5813     2.0           0     0  ...      8   
21610         1020      1350     2.0           0     0  ...      7   
21611         1600      2388     2.0           0     0  ...      8   
21612         1020      1076     2.0           0     0  ...      7   

       sqft_above  sqft_basement  yr_built  yr_renovated  zipcode      lat  \
0            1180              0      1955             0    98178  47.5112   
1            2170            400      1951          1991    98125  47.7210   
2             770              0      1933             0    98028  47.7379   
3            1050            910      1965             0    98136  47.5208   
4            1680              0      1987             0    98074  47.6168   
...           ...            ...       ...           ...      ...      ...   
21608        1530              0      2009             0    98103  47.6993   
21609        2310              0      2014             0    98146  47.5107   
21610        1020              0      2009             0    98144  47.5944   
21611        1600              0      2004             0    98027  47.5345   
21612        1020              0      2008             0    98144  47.5941   

          long  sqft_living15  sqft_lot15  
0     -122.257           1340        5650  
1     -122.319           1690        7639  
2     -122.233           2720        8062  
3     -122.393           1360        5000  
4     -122.045           1800        7503  
...        ...            ...         ...  
21608 -122.346           1530        1509  
21609 -122.362           1830        7200  
21610 -122.299           1020        2007  
21611 -122.069           1410        1287  
21612 -122.299           1020        1357  

[21613 rows x 21 columns]

In [33]:
X_casas = base_venda_de_casas.iloc[:, 3:19].values
X_casas

array([[ 3.00000e+00,  1.00000e+00,  1.18000e+03, ...,  9.81780e+04,
         4.75112e+01, -1.22257e+02],
       [ 3.00000e+00,  2.25000e+00,  2.57000e+03, ...,  9.81250e+04,
         4.77210e+01, -1.22319e+02],
       [ 2.00000e+00,  1.00000e+00,  7.70000e+02, ...,  9.80280e+04,
         4.77379e+01, -1.22233e+02],
       ...,
       [ 2.00000e+00,  7.50000e-01,  1.02000e+03, ...,  9.81440e+04,
         4.75944e+01, -1.22299e+02],
       [ 3.00000e+00,  2.50000e+00,  1.60000e+03, ...,  9.80270e+04,
         4.75345e+01, -1.22069e+02],
       [ 2.00000e+00,  7.50000e-01,  1.02000e+03, ...,  9.81440e+04,
         4.75941e+01, -1.22299e+02]])

In [34]:
y_casas = base_venda_de_casas.iloc[:, 2].values
y_casas

array([221900., 538000., 180000., ..., 402101., 400000., 325000.])

In [50]:
from sklearn.model_selection import train_test_split
X_casas_treinamento, X_casas_teste, y_casas_treinamento, y_casas_teste = train_test_split(X_casas, y_casas, test_size=0.3, random_state=0)

In [51]:
X_casas_treinamento.shape

(15129, 16)

In [52]:
X_casas_teste.shape

(6484, 16)

In [67]:
# IMPORTACAO DAS CARACTERISTICAS POLINOMIARES
from sklearn.preprocessing import PolynomialFeatures
poly = PolynomialFeatures(degree=2)
X_casas_treinamento_poly = poly.fit_transform(X_casas_treinamento)
X_casas_teste_poly = poly.transform(X_casas_teste)

In [68]:
X_casas_treinamento_poly.shape # Dados transformados e polinomios

(15129, 153)

In [69]:
X_casas_teste_poly.shape # Dados transformados e polinomios

(6484, 153)

In [70]:
from sklearn.linear_model import LinearRegression
regressor_casas_polinomio = LinearRegression()
regressor_casas_polinomio.fit(X_casas_treinamento_poly, y_casas_treinamento)

LinearRegression()

In [71]:
regressor_casas_polinomio.score(X_casas_treinamento_poly, y_casas_treinamento)

0.8179393211228992

In [72]:
regressor_casas_polinomio.score(X_casas_teste_poly, y_casas_teste)

0.8153400098995593

In [73]:
# b0
regressor_X_casas_polinomio.intercept_

35620070194.17125

In [74]:
# b1 ...n
regressor_X_casas_polinomio.coef_

array([-1.65643932e+03,  9.95674187e+06, -1.57775215e+07,  4.18260152e+04,
       -3.67796587e+01, -1.61007366e+07,  9.81414587e+07,  4.19320099e+06,
        4.84796619e+06, -2.62653099e+07, -2.95312923e+01, -3.92429178e+04,
       -4.00398054e+05,  4.20094348e+04, -8.36038672e+05,  3.93039139e+07,
       -8.03943060e+07,  7.98380434e+02, -7.96445635e+03, -2.73211412e+00,
        1.17263147e-02,  1.69128117e+04,  1.56112446e+04,  2.95293886e+03,
       -7.39071314e+03, -7.62797355e+02, -7.67923434e+00,  2.03776669e+00,
       -6.74812942e+01, -9.96648528e+00, -1.74496111e+01, -2.93096750e+04,
        5.47310445e+04, -3.70109465e+03,  1.21430837e+01, -2.70588849e-01,
       -3.47710615e+04, -1.67332008e+04,  3.84066432e+03, -6.23462512e+03,
        1.36765802e+04,  2.13536695e+01, -9.13139878e+00,  3.01928807e+02,
       -1.48263550e+01,  3.53172820e+01,  4.70271665e+04, -7.73716068e+04,
       -5.41553235e+01,  3.76614282e+03, -3.64884034e+00,  9.91289667e+01,
       -2.86646827e+00,  

In [76]:
previsao = regressor_casas_polinomio.predict(X_casas_teste_poly)
previsao # Dados previstos

array([ 386511.55485535, 1990814.4158783 ,  578824.15898132, ...,
        433146.82847595,  234282.00984192,  123653.67539978])

In [78]:
y_casas_teste # Dados reais

array([ 297000., 1578000.,  562100., ...,  380000.,  268000.,  206000.])

In [80]:
# analise do erro absoluto
from sklearn.metrics import mean_absolute_error
mean_absolute_error(y_casas_teste, previsao)

101223.19287563326